[package]
name = "bevy_hexasphere"
version = "0.1.2"
authors = ["OptimisticPeach <patrikbuhring@gmail.com>"]
edition = "2018"
description = """
A trimmed down and generic version of Hexasphere for bevy.
"""
readme = "readme.md"
repository = "https://github.com/OptimisticPeach/hexasphere.git"
license = "MPL-2.0"
keywords = ["gamedev", "graphics", "hexagons", "sphere", "math"]
categories = ["algorithms", "data-structures", "graphics", "mathematics", "rendering::data-formats"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"

[dev-dependencies]
glam = "0.13.0"

